services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      PGDATA: /data/postgres
    restart: unless-stopped
    ports:
      - ${DB_PORT}:5432
    expose:
      - "${DB_PORT}"

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080

  users-migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    entrypoint: [
      "migrate", "-path", "/migrations", "-database",
      "postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_DATABASE}?sslmode=disable", "up"
    ]
    restart: on-failure
    depends_on:
      - postgres

  users:
    image: avran02/decoplan-files
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - LOAD_DOT_ENV=false
      - SERVER_LOG_LEVEL=${SERVER_LOG_LEVEL}
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_HOST=${SERVER_HOST}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
    ports:
      - 50051:50051
    depends_on:
      - postgres
    restart: unless-stopped
