import LayoutClient from "@/components/layout/Layout"
import type { Metadata } from "next"
import localFont from "next/font/local"
import "./globals.scss"
import { Providers } from "./Providers"

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
})
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
})
const Monocraft = localFont({
	src: "./fonts/Monocraft.woff",
	variable: "--font-monocraft",
	weight: "100 900",
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`${Monocraft.variable} antialiased`}>
				<LayoutClient>
					<Providers>{children}</Providers>
				</LayoutClient>
			</body>
		</html>
	)
}
